In [284]:
# importing the numpy library
import numpy as np

In [285]:
print("cos(pi)           = ", np.cos(np.pi))
print('sqaure root(1.21) = ',np.sqrt(1.21))
print(np.log(np.exp(5.2)))

cos(pi)           =  -1.0
sqaure root(1.21) =  1.1
5.2


In [286]:
#List in Arrays
list = [4, 2, 1 ,6, 7]

#Converting to vectors using numpy
vec = np.array(list)
print(vec.ndim,'Dimensionsal:\n')
print(vec)
print('')

#Converting to matrix using numpy
matrix = np.array([[3, 2, 1], [4, 8, 9], [3, 6, 7]])
print(matrix.ndim,'Dimensional:\n')
print(matrix)

#Transpose of mtrix using numpy
print('\nTranspose:\n\n', matrix.T)

1 Dimensionsal:

[4 2 1 6 7]

2 Dimensional:

[[3 2 1]
 [4 8 9]
 [3 6 7]]

Transpose:

 [[3 4 3]
 [2 8 6]
 [1 9 7]]


In [287]:
#Printing 1D array
for i in vec:
  print(i, end = " ")
print('')

#Printing 2D Array
for i in matrix:
  print('')
  for j in i:
    print(j, end = " ")   
print('')
print('')

#Printing 2D Array
for x in np.nditer(matrix):
  print(x, end = " ") 

4 2 1 6 7 

3 2 1 
4 8 9 
3 6 7 

3 2 1 4 8 9 3 6 7 

In [288]:
#Slicing
print(vec[:])
print(vec[0:])
print(vec[2:5])
print(vec[::2])
print(vec[::-1])

[4 2 1 6 7]
[4 2 1 6 7]
[1 6 7]
[4 1 7]
[7 6 1 2 4]


In [289]:
#Views
view1 = vec.copy()
vec[2] = 0
view2 = vec.copy()
view2[2]= 5

print(vec)
print(view1)
print(view2)

[4 2 0 6 7]
[4 2 1 6 7]
[4 2 5 6 7]


In [290]:
#where
print(np.where(vec == 6))
print(np.where(vec % 2 != 0)) 
print(np.where(vec % 2 == 0)) 

(array([3]),)
(array([4]),)
(array([0, 1, 2, 3]),)


In [291]:
#sort and binary search
print(np.sort(vec))
print(vec)
print(np.searchsorted(np.sort(vec), 2))
print(np.searchsorted(np.sort(vec), [2, 6, 9]))
vec = np.sort(vec)
print(vec)
print(np.searchsorted(vec, 7))

[0 2 4 6 7]
[4 2 0 6 7]
1
[1 3 5]
[0 2 4 6 7]
4
